on:
  push:
    branches:
      - main
      - master

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
#           server: ${{ secrets.KINDLEGATE_FTP_SERVER }}
          server: ftp.kindlegatefoundation.org
          username: ${{ secrets.KINDLEGATE_FTP_USERNAME }}
          password: ${{ secrets.KINDLEGATE_FTP_PASSWORD }}
          local-dir: dist/
